ARG CUDA_VERSION="11.8.0"
ARG CUDNN_VERSION="8"
ARG UBUNTU_VERSION="22.04"
# Base NVidia CUDA Ubuntu image
FROM nvidia/cuda:${CUDA_VERSION}-cudnn${CUDNN_VERSION}-devel-ubuntu${UBUNTU_VERSION}

# Set environment variable for non-interactive installations
ENV DEBIAN_FRONTEND=noninteractive

# Set up environment variables
ENV HOME /root
WORKDIR $HOME
ENV PYTHON_VERSION=3.9
ENV PATH="/usr/local/cuda/bin:${PATH}"

# --- System & Conda Setup ---
# Install system dependencies and Miniconda in a single layer to reduce image size.
ENV PATH="${HOME}/miniconda3/bin:${PATH}" # Add conda to the default path
RUN apt-get update && apt-get install -y --no-install-recommends \
        zsh wget tmux tldr nvtop vim neovim curl rsync \
        net-tools less iputils-ping p7zip-full zip unzip git-lfs \
    # Install Miniconda for Python environment management
    && wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O Miniconda.sh \
    && mkdir -p ${HOME}/.conda \
    && bash Miniconda.sh -b -p ${HOME}/miniconda3 \
    && rm -f Miniconda.sh \
    # Clean up apt cache
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# --- Conda Environment Creation ---
ENV CONDA=pytorch
RUN conda update -n base conda -y \
    && conda init bash \
    && conda create -n "${CONDA}" python="${PYTHON_VERSION}" -y
ENV PATH="${HOME}/miniconda3/envs/${CONDA}/bin:${PATH}" # Activate the conda environment by default

# --- Git Configuration ---
# Set up git to support LFS and store credentials for services like Huggingface Hub.
RUN git config --global credential.helper store && \
    git lfs install
